# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-29 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('popolo', '0002_update_models_from_upstream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('popolo.person',),
        ),
    ]
